/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Kontroler;
import niti.BingoNit;
import niti.PokreniServer;

/**
 *
 * @author frado
 */
public class ServerskaForma extends javax.swing.JFrame {
    
    BingoNit bn;

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        generisiBrojeve();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_stop = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();
        btn_sacuvajIgru = new javax.swing.JButton();
        btn_pokreniIgru = new javax.swing.JButton();
        lbl_PrviBroj = new javax.swing.JLabel();
        lbl_DrugiBroj = new javax.swing.JLabel();
        lbl_CetvrtiBroj = new javax.swing.JLabel();
        lbl_TreciBroj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_stop.setText("STOP");
        btn_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stopActionPerformed(evt);
            }
        });

        btn_start.setText("START");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        btn_sacuvajIgru.setText("SACUVAJ IGRU");
        btn_sacuvajIgru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sacuvajIgruActionPerformed(evt);
            }
        });

        btn_pokreniIgru.setText("POKRENI IGRU");
        btn_pokreniIgru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pokreniIgruActionPerformed(evt);
            }
        });

        lbl_PrviBroj.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_PrviBroj.setText("0");

        lbl_DrugiBroj.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_DrugiBroj.setText("0");

        lbl_CetvrtiBroj.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_CetvrtiBroj.setText("0");

        lbl_TreciBroj.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_TreciBroj.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_pokreniIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sacuvajIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lbl_PrviBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lbl_DrugiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lbl_TreciBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(lbl_CetvrtiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PrviBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_DrugiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_CetvrtiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TreciBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pokreniIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sacuvajIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
        
        bn.radi = false;
        
    }//GEN-LAST:event_btn_stopActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        
        bn = new BingoNit(lbl_PrviBroj, lbl_DrugiBroj, lbl_TreciBroj, lbl_CetvrtiBroj, true);
        bn.start();
        
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_sacuvajIgruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sacuvajIgruActionPerformed
        
        try {
            boolean uspesno = Kontroler.getInstance().sacuvajIgru();
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Uspesno sacuvana igra");
            }
            else{
                JOptionPane.showMessageDialog(this, "Nije sacuvana igra");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ServerskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btn_sacuvajIgruActionPerformed

    private void btn_pokreniIgruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pokreniIgruActionPerformed
        
        PokreniIgru.PrekiniIgru = false;
        
        int prviBroj = Integer.parseInt(lbl_PrviBroj.getText());
        int drugiBroj = Integer.parseInt(lbl_DrugiBroj.getText());
        int treciBroj = Integer.parseInt(lbl_TreciBroj.getText());
        int cetvrtiBroj = Integer.parseInt(lbl_CetvrtiBroj.getText());
        
        
        int[] niz = new int[4];
        niz[0] = prviBroj;
        niz[1] = drugiBroj;
        niz[2] = treciBroj;
        niz[3] = cetvrtiBroj;
        
        Kontroler.getInstance().setDobitnaKombinacija(niz);
        
    }//GEN-LAST:event_btn_pokreniIgruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
                PokreniServer ps = new PokreniServer();
                ps.start();
            }
        });
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pokreniIgru;
    private javax.swing.JButton btn_sacuvajIgru;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel lbl_CetvrtiBroj;
    private javax.swing.JLabel lbl_DrugiBroj;
    private javax.swing.JLabel lbl_PrviBroj;
    private javax.swing.JLabel lbl_TreciBroj;
    // End of variables declaration//GEN-END:variables

    private void generisiBrojeve() {
        
        long prviBroj = Math.round(Math.random() * 5);
        long drugiBroj = Math.round(Math.random() * 5);
        long treciBroj = Math.round(Math.random() * 5);
        long cetvrtiBroj = Math.round(Math.random() * 5);
        
        lbl_PrviBroj.setText(String.valueOf(prviBroj));
        lbl_DrugiBroj.setText(String.valueOf(drugiBroj));
        lbl_TreciBroj.setText(String.valueOf(treciBroj));
        lbl_CetvrtiBroj.setText(String.valueOf(cetvrtiBroj));
        
    }
}
